[package]
name = "animal_game_ecs_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = "2.0.29"
bevy_ecs = "0.11.2"
proc-macro2 = "1.0.66"